server.port: 8082
spring:
  application:
    name: api-gateway
  devtools:
    restart:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: users-status-check
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users/status
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookies
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: users-create
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookies
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
        - id: users-login
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookies
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

token:
  expiration_time: 3600000
  secret: qma78k1bkp48xzbd6vczrwutxa4ueg1uzm2ukrdk9ssrozg88v