spring:
  application:
    name: photo-app-discovery-service

server:
  port: 8010

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka