server:
  port: 8012

management:
  endpoints:
    web:
      exposure:
        include: busrefresh


spring:
  application:
    name: PhotoAppConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Lordgrim999/PhotoAppConfiguration
          username: Lordgrim999
          password: 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
          clone-on-start: true
          default-label: main
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
